# Generated by Django 5.1.5 on 2025-02-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
