# Generated by Django 5.1.7 on 2025-04-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
